version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "5000:80"
      volumes:
          - ./app:/var/app
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
      environment:
          - "DB_HOST=db"
          - "DB_DATABASE=gaxze"
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=gaxze
      volumes:
          - ./database:/var/lib/mysql